name: BNK Bot 3
version: "1.0"
slug: bnk_bot_3
description: Telegram-бот для учёта продукции и брака
startup: application
boot: auto
host_network: true
hassio_api: true
hassio_role: default
init: false
build: .
arch:
  - aarch64
options:
  TELEGRAM_TOKEN: "8199873882:AAE4x2ARLf7bR0fC9ykeOyHsrinT9JPIdRM"
schema:
  TELEGRAM_TOKEN: str
environment:
  TELEGRAM_TOKEN: "{options.TELEGRAM_TOKEN}"  
