name: BNK_BOT2
version: "1.1.9"
slug: bnk_bot_3
description: Telegram-бот для учёта продукции и брака
startup: application
boot: auto
host_network: true
hassio_api: true
hassio_role: default
init: false
build: .
arch:
  - aarch64
map:
  - config:rw  
options:
  TELEGRAM_TOKEN: ""
schema:
  TELEGRAM_TOKEN: str
