name: BNK Bot 3
version: "1.0"
slug: bnk_bot_3
description: Telegram-бот для учёта продукции и брака
startup: application
boot: auto
host_network: true
hassio_api: true
hassio_role: default
init: false
image: local/bnk-bot-3
build: .
arch:
  - aarch64
options:
  TELEGRAM_TOKEN: ""
schema:
  TELEGRAM_TOKEN: str